"""Initial migration for clipnest

Revision ID: 4a07e9f43dd8
Revises: 
Create Date: 2026-07-04 15:04:56.865358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a07e9f43dd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipnest_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipnest_users_email'), 'clipnest_users', ['email'], unique=True)
    op.create_index(op.f('ix_clipnest_users_id'), 'clipnest_users', ['id'], unique=False)
    op.create_table('clipnest_activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['clipnest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipnest_activity_logs_id'), 'clipnest_activity_logs', ['id'], unique=False)
    op.create_table('clipnest_bookmarks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['clipnest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipnest_bookmarks_id'), 'clipnest_bookmarks', ['id'], unique=False)
    op.create_table('clipnest_collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['clipnest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipnest_collections_id'), 'clipnest_collections', ['id'], unique=False)
    op.create_table('clipnest_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['clipnest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipnest_tags_id'), 'clipnest_tags', ['id'], unique=False)
    op.create_table('clipnest_bookmark_tags',
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['clipnest_bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['clipnest_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'tag_id')
    )
    op.create_table('clipnest_collection_bookmarks',
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['clipnest_bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['clipnest_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'bookmark_id')
    )
    op.create_table('clipnest_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bookmark_id'], ['clipnest_bookmarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmark_id')
    )
    op.create_index(op.f('ix_clipnest_notes_id'), 'clipnest_notes', ['id'], unique=False)
    op.create_table('clipnest_pdfs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bookmark_id'], ['clipnest_bookmarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmark_id')
    )
    op.create_index(op.f('ix_clipnest_pdfs_id'), 'clipnest_pdfs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clipnest_pdfs_id'), table_name='clipnest_pdfs')
    op.drop_table('clipnest_pdfs')
    op.drop_index(op.f('ix_clipnest_notes_id'), table_name='clipnest_notes')
    op.drop_table('clipnest_notes')
    op.drop_table('clipnest_collection_bookmarks')
    op.drop_table('clipnest_bookmark_tags')
    op.drop_index(op.f('ix_clipnest_tags_id'), table_name='clipnest_tags')
    op.drop_table('clipnest_tags')
    op.drop_index(op.f('ix_clipnest_collections_id'), table_name='clipnest_collections')
    op.drop_table('clipnest_collections')
    op.drop_index(op.f('ix_clipnest_bookmarks_id'), table_name='clipnest_bookmarks')
    op.drop_table('clipnest_bookmarks')
    op.drop_index(op.f('ix_clipnest_activity_logs_id'), table_name='clipnest_activity_logs')
    op.drop_table('clipnest_activity_logs')
    op.drop_index(op.f('ix_clipnest_users_id'), table_name='clipnest_users')
    op.drop_index(op.f('ix_clipnest_users_email'), table_name='clipnest_users')
    op.drop_table('clipnest_users')
    # ### end Alembic commands ###
