"""Add annotation table

Revision ID: a7443945550b
Revises: e018c0344745
Create Date: 2026-07-05 13:17:18.529054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7443945550b'
down_revision: Union[str, Sequence[str], None] = 'e018c0344745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipnest_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('highlight_text', sa.String(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bookmark_id'], ['clipnest_bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['clipnest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clipnest_annotations_id'), 'clipnest_annotations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clipnest_annotations_id'), table_name='clipnest_annotations')
    op.drop_table('clipnest_annotations')
    # ### end Alembic commands ###
